Dataset: https://www.kaggle.com/datasets/prasad22/healthcare-dataset

## Import libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

## Data analysis

In [4]:
df = pd.read_csv("../../data/healthcare_dataset.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
col = df.columns.to_list()
print("Columns:")
print(col)
target = df['Test Results']
print("\nTypes of result:")
target.unique()

Columns:
['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']

Types of result:

<StringArray>
['Normal', 'Inconclusive', 'Abnormal']
Length: 3, dtype: str

In [6]:
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.lower()
df.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## Feature Importance
We want to check the features that influence the test_results, and to change categorical features to numerical.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                55500 non-null  str
 1   age                 55500 non-null  int64
 2   gender              55500 non-null  str
 3   blood_type          55500 non-null  str
 4   medical_condition   55500 non-null  str
 5   date_of_admission   55500 non-null  str
 6   doctor              55500 non-null  str
 7   hospital            55500 non-null  str
 8   insurance_provider  55500 non-null  str
 9   billing_amount      55500 non-null  float64
 10  room_number         55500 non-null  int64
 11  admission_type      55500 non-null  str
 12  discharge_date      55500 non-null  str
 13  medication          55500 non-null  str
 14  test_results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

We could see that the features like name, doctor, hospital do not influence the test results. We will drop these columns.

In [8]:
new_df = df.copy()

new_df = new_df.drop(columns=[
    "name",
    "doctor",
    "hospital",
    "date_of_admission",
    "discharge_date",
    "room_number"
])
new_df

,age,gender,blood_type,medical_condition,insurance_provider,billing_amount,admission_type,medication,test_results
0,30,Male,B-,Cancer,Blue Cross,18856.281306,Urgent,Paracetamol,Normal
1,62,Male,A+,Obesity,Medicare,33643.327287,Emergency,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,Aetna,27955.096079,Emergency,Aspirin,Normal
3,28,Female,O+,Diabetes,Medicare,37909.782410,Elective,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,Aetna,14238.317814,Urgent,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...
55495,42,Female,O+,Asthma,Blue Cross,2650.714952,Elective,Penicillin,Abnormal
55496,61,Female,AB-,Obesity,Cigna,31457.797307,Elective,Aspirin,Normal
55497,38,Female,B+,Hypertension,UnitedHealthcare,27620.764717,Urgent,Ibuprofen,Abnormal
55498,43,Male,O-,Arthritis,Medicare,32451.092358,Elective,Ibuprofen,Abnormal
55499,53,Female,O+,Arthritis,Aetna,4010.134172,Urgent,Ibuprofen,Abnormal

In [9]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 55500 non-null  int64
 1   gender              55500 non-null  str
 2   blood_type          55500 non-null  str
 3   medical_condition   55500 non-null  str
 4   insurance_provider  55500 non-null  str
 5   billing_amount      55500 non-null  float64
 6   admission_type      55500 non-null  str
 7   medication          55500 non-null  str
 8   test_results        55500 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 3.8 MB

In [10]:
new_df.describe(include='str')

,gender,blood_type,medical_condition,insurance_provider,admission_type,medication,test_results
count,55500,55500,55500,55500,55500,55500,55500
unique,2,8,6,5,3,5,3
top,Male,A-,Arthritis,Cigna,Elective,Lipitor,Abnormal
freq,27774,6969,9308,11249,18655,11140,18627

## Training model

In [28]:
X = new_df.drop(columns=["test_results"])

le = LabelEncoder()
y = le.fit_transform(new_df["test_results"])

In [29]:
# One-Hot Encoding for categorical data
X = pd.get_dummies(X, drop_first=True)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [32]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.4327927927927928
              precision    recall  f1-score   support

           0       0.43      0.44      0.44      3726
           1       0.43      0.42      0.43      3671
           2       0.43      0.44      0.43      3703

    accuracy                           0.43     11100
   macro avg       0.43      0.43      0.43     11100
weighted avg       0.43      0.43      0.43     11100

### XGBoost

In [33]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="mlogloss"
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [34]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.3581081081081081
              precision    recall  f1-score   support

           0       0.36      0.38      0.37      3726
           1       0.36      0.34      0.35      3671
           2       0.36      0.35      0.35      3703

    accuracy                           0.36     11100
   macro avg       0.36      0.36      0.36     11100
weighted avg       0.36      0.36      0.36     11100

## CatBoost

In [37]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(verbose=0)
model.fit(X_train, y_train)

CatBoostClassifier(verbose=0)

In [38]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.36423423423423423
              precision    recall  f1-score   support

           0       0.37      0.38      0.37      3726
           1       0.36      0.35      0.36      3671
           2       0.36      0.36      0.36      3703

    accuracy                           0.36     11100
   macro avg       0.36      0.36      0.36     11100
weighted avg       0.36      0.36      0.36     11100

In [39]:
df["test_results"].value_counts(normalize=True)

test_results
Abnormal        0.335622
Normal          0.333640
Inconclusive    0.330739
Name: proportion, dtype: float64

In [41]:
import pandas as pd

for col in new_df.columns:
    if col != "test_results":
        print(col, new_df.groupby(col)["test_results"].value_counts(normalize=True).head())

age age  test_results
13   Abnormal        0.571429
     Inconclusive    0.214286
     Normal          0.214286
14   Normal          0.444444
     Abnormal        0.277778
Name: proportion, dtype: float64
gender gender  test_results
Female  Abnormal        0.336796
        Inconclusive    0.332396
        Normal          0.330809
Male    Normal          0.336466
        Abnormal        0.334449
Name: proportion, dtype: float64
blood_type blood_type  test_results
A+          Abnormal        0.335394
            Inconclusive    0.334963
            Normal          0.329643
A-          Abnormal        0.335199
            Normal          0.335055
Name: proportion, dtype: float64
medical_condition medical_condition  test_results
Arthritis          Abnormal        0.342501
                   Inconclusive    0.331758
                   Normal          0.325741
Asthma             Normal          0.342624
                   Inconclusive    0.329777
Name: proportion, dtype: float64
insurance_provider insurance_provider  test_results
Aetna               Inconclusive    0.335380
                    Abnormal        0.332722
                    Normal          0.331898
Blue Cross          Inconclusive    0.337463
                    Normal          0.333574
Name: proportion, dtype: float64
billing_amount billing_amount  test_results
-2008.492140    Abnormal        1.0
-1660.009373    Normal          1.0
-1520.420555    Abnormal        1.0
-1428.843941    Abnormal        1.0
-1316.618581    Inconclusive    1.0
Name: proportion, dtype: float64
admission_type admission_type  test_results
Elective        Abnormal        0.337497
                Normal          0.334548
                Inconclusive    0.327955
Emergency       Normal          0.334227
                Abnormal        0.333406
Name: proportion, dtype: float64
medication medication  test_results
Aspirin     Normal          0.336939
            Abnormal        0.336398
            Inconclusive    0.326663
Ibuprofen   Abnormal        0.336748
            Normal          0.335670
Name: proportion, dtype: float64

We could see that the propotion is almost the same (~0.33) for every class. This means the distributions are almost identical everywhere, the dataset has no predictive signal.

This is a dummy dataset and is better to EDA and visualize. It is not useful for classification task.